[project]
name = "2024KRelection_commentary"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.12.*"
jupyter = ">=1.0.0,<1.1"
pandas = ">=2.2.2,<2.3"
pyarrow = ">=15.0.2,<15.1"
